#pragma once
#define EXIT -1
#define SUCCESS 0
#define UNKNOWN_ERROE_WHEN_PARSING 1
#define NOT_EXISTING_TABLE_NAME 2
#define EXISTING_TABLE_NAME 3
#define NOT_EXISTING_COLUMN_NAME 4
#define EXISTING_COLUMN_NAME 5
#define NOT_EXISTING_INDEX_NAME 6
#define EXISTING_INDEX_NAME 7
#define NON_UNIQUE_PRIMARY_KEY 1000
#define MAX_CHAR_LENGTH_EXCEEDED 1001
#define UNKNOWN_PRIMARY_KEY 1003
#define DELETE_TABLE_FAILED 2000
#define WRONG_VALUE_COUNT 2001
#define BAD_VALUE 2002
#define DUPLICATED_UNIQUE_KEY 2003